[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Cheng XU <rust@xuc.me>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0"
bytecount = "0.6"
itertools = "0.8"
num = "0.1"
petgraph = "0.4"
regex = "1.3"
